package com.termux.terminal;

/**
 * Receives bytes that the terminal wants to send to the remote side: keys typed by the user and
 * responses generated by the emulator (e.g. cursor position reports, device attribute replies).
 * <p>
 * The application forwards these bytes to the remote tmux pane.
 */
public interface TerminalSink {

    void write(byte[] data, int offset, int count);

}
